### ISSUE TITLE
Error with packagetracer.xlsm

### ISSUE THREAD

**Issue by VBlackie** [fzumstein/python-for-excel#13]
Hi, I've found an error but not sure how to fix it. I have tried going over forums including the one on xlwings but no luck yet.

**What?**
Got a Error: TypeError message when using the pagetracker.xlsm file

**Steps to reproduce**
- Using Windows 10
- Using Excel for Mircosoft 365
- PyCharm Community Edition
- Python 3.11

On Chapter 11 we are introduced to a packagetrackre.xlsm I enabled the macros and all. I am on the Database sheet and just clic the 'Add Package' button after "xlwings" was added at the package name slot but got: "Error: TypeError("Connection.execute() got an unexpected keyword argument 'package_name'")"
![2023-08-25 11_25_54-Window](https://github.com/fzumstein/python-for-excel/assets/45616834/e6c936f0-ada6-40f6-918f-6dbc9b50881b)
. I was expecting for the "package added" prompt but nope. I tried ussing other packages as pandas but the same thing occurs.

**Debugging**
I checked on the packagetracker.py file and found that message was given as a general error message in case other errors wouldn;t appear so I haven't been able to figure out what's going on. I found the package name variable, but seems to be trying to fetch the value of the cell in excel.

It;s dving me insane now how I just dont know how to stop getting that error message or how to fix it. Please help.

**Comment by fzumstein** [comment]
Are you using the workbook/code from this repo or were you putting it together manually?

**Comment by VBlackie** [comment]
I was using the one from here. Downloaded the zip file.

**Comment by fzumstein** [comment]
And which version of Anaconda have you got installed?

**Comment by VBlackie** [comment]
my conda version is 23.7.3

**Comment by fzumstein** [comment]
I've just downloaded the latest Anaconda installer and ran it with the downloaded code from the ZIP and couldn't replicate your issue. Can you copy/paste the your `store_package` function from the `database.py` file?

**Comment by VBlackie** [comment]
Sure!

def store_package(package_name):
    """Insert a new package_name into the packages table"""

    try:
        with engine.connect() as con:
            con.execute(text("INSERT INTO packages (package_name) VALUES (:package_name)"),
                        package_name=package_name)
        return None
    except sqlalchemy.exc.IntegrityError:
        return f"{package_name} already exists"
    except Exception as e:
        return repr(e)

this one??

**Comment by fzumstein** [comment]
You must have upgraded the sqlalchemy package to 2.0. Note that Anaconda still in its latest version comes with 1.4.39, which is compatible with the code in the book.

My suggestion would be to downgrade like this: `pip install sqlalchemy==1.4.39` or to use the dedicated conda env, as described in the Appendix of the book or here on the homepage: https://www.xlwings.org/book#pythonanaconda-version

**Comment by VBlackie** [comment]
All right, let me give it a try with that one! I'll let you know if it works.

**Comment by AhmadKhanSenpai** [comment]
I got the same problem but I figured it out what was triggering it. This problem occurs when you have different version of xlwings installed on the windows but you are using the xlwings module version from the environement.yml file. So If you click the Add Package button or Show Summary Buttons, you will get an error but if you run the packagetracker.py file from the terminal and use the following snippet to mock the call from the packagetracker.py file it will run just fine.
```
if __name__ == "__main__":
    xw.Book("packagetracker.xlsm").set_mock_caller()
    show_history()
```
I forked your repo and I am going to modify the code that will run for the latest version as well because new readers might get this error and get annoyed that the code is not updated and it is not even working on the environment that the Author used.

**Comment by fzumstein** [comment]
Following the book's instructions, you shouldn't end up in this situation: the book explains how to install the conda env using `xl38.yml`, not `environment.yml`. The latter is only there for the Binder online Jupyter notebook service, as mentioned at the top of the file.

**Comment by AhmadKhanSenpai** [comment]
Even though I debugged the packagetracker according to latest versions of all modules but I reproduced the Error and figured out what was causing it. It seems that you also have to give conda path and env that you make with ```xl38.yml``` to xlwings tab in Excel:

![Screenshot_2](https://github.com/fzumstein/python-for-excel/assets/50776448/a13bdebb-dafa-4ae4-af80-661044260862)
  
![Screenshot_3](https://github.com/fzumstein/python-for-excel/assets/50776448/3e500afb-6fe5-46dc-9c20-0fd64d439bf1)

and when you give the path and env name, it works from ```xlsm``` sheet as well. I don't know if this step is included in the book or not because I don't remember. and ```xlwings``` version difference don't have anything to do with this error because I am using ```xlwings 0.30.12``` as you can see in screenshot but in conda env i just updated to ```xlwings 0.29```  

![Screenshot_1](https://github.com/fzumstein/python-for-excel/assets/50776448/7f056b9e-3053-487d-ba15-e881b4fb63e9)

**Comment by fzumstein** [comment]
Right, thanks for pointing that out! Well, the instructions are to use `(xl38)` whenever the book uses `(base)`, so in that case you'd run the add-in's install command (`xlwings addin install`) from an Anaconda prompt with `(xl38)` activated, which will properly configure the add-in automatically.

I'll improve the instructions on how to set up a working environment in the next edition.
